routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(["prefix"=>"/"],function(){
	Route::get('/','Theme\RovaController@index')->name('web.index');
    Route::post('/post_mail','Theme\RovaController@post_mail')->name('web.post_mail');
    Route::get('danh-muc/{url}','Theme\RovaController@categories')->name('web.categories');
    Route::get('tags/{url}','Theme\RovaController@tags')->name('web.tags');
    Route::get('gioi-thieu/{id}','Theme\RovaController@aboutUs')->name('web.about.us');
    Route::get('lien-he','Theme\RovaController@contact')->name('web.contact');
    Route::get('chi-tiet/{id}','Theme\RovaController@chi_tiet')->name('web.chi_tiet');
    Route::get('san-pham/{id}','Theme\RovaController@san_pham')->name('web.san_pham');
    Route::get('bai-viet/{id}','Theme\RovaController@chi_tiet_tin')->name('web.chi_tiet_tin');
    Route::get('chuong-trinh-khuyen-mai','Theme\RovaController@client')->name('web.client');
    Route::get('chi-tiet-tin/{id}','Theme\RovaController@show_post')->name('web.show_post');
    Route::get('gio-hang','Theme\RovaController@cart')->name('web.cart');
    Route::get('thanh-toan','Theme\RovaController@payment')->name('web.payment');
    Route::get('tin-tuc/{id}','Theme\RovaController@post')->name('web.post');
    // Route::get('parador/{url}.html','Theme\RovaController@post')->name('web.post');
//    Route::get('san-go-parador','Theme\RovaController@products')->name('web.products');
//    Route::get('san-go-parador/{url}.html','Theme\RovaController@product')->name('web.product');
//    Route::get('san-go-parador-cao-cap/{url}.html','Theme\RovaController@productCate')->name('web.product.category');
//    Route::get('dai-ly-parador','Theme\RovaController@agents')->name('web.agents');
    Route::post('data-for-contact','Theme\RovaController@contactPost')->name('web.contact.post');
    Route::get('ho-tro-khach-hang','Theme\RovaController@member')->name('web.member');
    Route::get('loi-khong-tim-thay-trang-404','Theme\RovaController@error')->name('web.error');
    Route::get('update-cart','Theme\RovaController@updateCart')->name('web.update.cart');
    Route::get('remove-cart','Theme\RovaController@removeCart')->name('web.remove.cart');
});
Route::get('component/slider','ComponentController@slider')->name('components.slider');
/**
 *Backend adminstrator
**/
Auth::routes();
// view onlypage
	Route::get('admin/dashboard', 'HomeController@index')->name('dashboard');
	Route::get('admin/', 'HomeController@index')->name('admin');

Route::group(['prefix'=>'admin/','middleware' => ['auth']],function(){
//    user route
    Route::get('users','UserController@index')->name('user.list');
    Route::get('user/{id}','UserController@show')->name('user.show');
    Route::get('user/edit/{id}','UserController@edit')->name('user.edit');
    Route::get('user/delete/{id}','UserController@delete')->name('user.delete');
    Route::post('user/{id}','UserController@update')->name('user.update');
    Route::post('users','UserController@store')->name('user.store');
// manager file and backend custom
    Route::get('manager-file', 'BackendController@managerFile')->name('manager.file');
    Route::get('command', 'BackendController@runCommand')->name('command');
    Route::post('command', 'BackendController@postCommand')->name('command');
    Route::get('hoang-config/google-analytic','BackendController@google')->name('hoang.google');
    Route::get('hoang-config/facebook-pixel','BackendController@facebook')->name('hoang.facebook');
    Route::get('hoang-config/javascript','BackendController@javascript')->name('hoang.javascript');

//	config role of user
    Route::get('roles','RoleController@index')->name('roles.index');
    Route::get('roles/{id}/edit','RoleController@edit')->name('roles.edit');
    Route::get('roles/create','RoleController@create')->name('roles.create');
    Route::get('roles/{id}','RoleController@show')->name('roles.show');
    Route::get('roles/{id}','RoleController@destroy')->name('roles.destroy');
    Route::post('roles','RoleController@store')->name('roles.store');
    Route::post('roles/{id}','RoleController@update')->name('roles.update');
    Route::get('roles/error/403','RoleController@error')->name('roles.error');
	// Restfull function
	Route::resource('posts', PostsController::class);
    Route::get('slider','SlidersController@index')->name('slider.index');
    Route::post('slider-create','SlidersController@create')->name('slider.create');
    Route::get('slider-delete/{id}','SlidersController@destroy')->name('slider.destroy');
    Route::get('logo','LogosController@index')->name('logo.index');
    Route::post('logo-create','LogosController@create')->name('logo.create');
    Route::get('logo-delete/{id}','LogosController@destroy')->name('logo.destroy');
	Route::resource('pages', PagesController::class);
	Route::resource('products', ProductsController::class);
    Route::post('products/list-images','ProductsController@images')->name('products.images');
    Route::post('products/update-images/{id}','ProductsController@updateImages')->name('products.update.image');
    Route::get('products/images/delete/{id}','ProductsController@deleteImages')->name('products.image.delete');
    Route::get('products/edit-deal/{id}','ProductsController@editDeal')->name('products.edit.deal');


    Route::resource('categories', CategoriesController::class);
	Route::resource('tags', TagsController::class);
	Route::resource('menus', MenusController::class);
   // Route::get('menu-items/delete/{$id}','BackendController@deleteMenuItem')->name('menu-items.delete');

    Route::resource('menu-items', MenuItemsController::class);
	Route::resource('homes', HomesController::class);
	Route::resource('comments', CommentsController::class);
	Route::resource('configs', ConfigsController::class);
    Route::resource('contacts', ContactsController::class);


    Route::resource('events', EnventsController::class);
    Route::resource('members', MembersController::class);

    Route::resource('students', StudentsController::class);
    Route::resource('teachers', TeachersController::class);

    Route::resource('courses', CoursesController::class);
    Route::resource('lessons', LessonsController::class);
});

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Entities\Config;
use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function managerFile(){
    	return view('backend.manager-file');
    }
    public function runCommand(){
        return view('backend.command');
    }
    public function postCommand(Request $request){
        $command = $request->command;

        echo shell_exec('touch abcádassad');
        $abc = shell_exec('touch abcádasd');
        printf($abc);
        dd($command);
        return redirect()->back();
    }
    public function deleteMenuItem($id){
        dd($id);
        return view('menus.index');
    }
    public function google(){
        $data['google'] = Config::where('key','google')->first();
        return view('backend.analytic',$data);
    }
    public function facebook(){
        $data['facebook'] = Config::where('key','facebook')->first();
        return view('backend.facebookPixel',$data);
    }
    public function javascript(){
        $data['javascript'] = Config::where('key','javascript')->first();
        return view('backend.javascript',$data);
    }
}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\StudentCreateRequest;
use App\Http\Requests\StudentUpdateRequest;
use App\Repositories\StudentRepository;
use App\Validators\StudentValidator;

/**
 * Class StudentsController.
 *
 * @package namespace App\Http\Controllers;
 */
class StudentsController extends Controller
{
    /**
     * @var StudentRepository
     */
    protected $repository;

    /**
     * @var StudentValidator
     */
    protected $validator;

    /**
     * StudentsController constructor.
     *
     * @param StudentRepository $repository
     * @param StudentValidator $validator
     */
    public function __construct(StudentRepository $repository, StudentValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $students = $this->repository->paginate($limit = 10, $columns = ['*']);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $students,
            ]);
        }

        return view('backend.students.index', compact('students'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StudentCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(StudentCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $student = $this->repository->create($request->all());

            $response = [
                'message' => 'Student created.',
                'data'    => $student->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $student = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $student,
            ]);
        }

        return view('backend.students.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = $this->repository->find($id);

        return view('backend.students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  StudentUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(StudentUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $student = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Student updated.',
                'data'    => $student->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Student deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Student deleted.');
    }
}

resources/views/backend/students/create.blade.php
<form id="main" method="post" action="{{ route('students.store') }}" enctype="multipart/form-data"> @csrf
    <div class="row">
        <div class="col-sm-8">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    @if($errors->has('name'))
                        <span class="messages alert-danger">{{ $errors->first('name')}}</span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Full Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="fullname" value="{{ old('name') }}">
                    @if($errors->has('name'))
                        <span class="messages alert-danger">{{ $errors->first('fullname')}}</span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Address</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="address" value="{{ old('name') }}">
                    @if($errors->has('name'))
                        <span class="messages alert-danger">{{ $errors->first('fullname')}}</span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                    @if($errors->has('email'))
                        <span class="messages alert-danger">{{ $errors->first('email')}}</span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" value="{{ old('password') }}">
                    @if($errors->has('password'))
                        <span class="messages alert-danger">{{ $errors->first('password')}}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group row">
                <label class="col-sm-12 col-form-label">Status</label>
                <div class="col-sm-12">
                    <select name="status" class="form-control" >
                        <option value="1" selected>Active</option>
                        <option value="0">Disable</option>
                    </select>
                    <span class="messages"></span>
                </div>
            </div><div class="form-group row">
                <label class="col-sm-12 col-form-label">Image</label>
                <div class="col-sm-12">
                    <input type="file" class="form-control">
                    <span class="messages"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2"></label>
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary m-b-0">{{__('Submit')}}</button>
        </div>
    </div>
</form>

resources/views/backend/students/index.blade.php
@extends('layouts.admin.design')
@section('title','List teacher')
@section('content')
<?php
$status = [0=>'Pending',1=>'Draft',2=>'Published']
 ?>
<div class="row">                    
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>List data</h5>
                <span>Descreption</span>
                <div class="card-header-right">
                    <i class="icofont icofont-rounded-down"></i>
                </div>
                <button type="button" class="btn btn-primary waves-effect" data-toggle="modal" data-target="#large-Modal">Add Teacher</button>
                {{--<div class="modal fade show" id="large-Modal" tabindex="-1" role="dialog" style="display: block;">--}}
                <div class="modal fade show" id="large-Modal" tabindex="-1" role="dialog" >
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Add Teacher</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                @include('backend.students.create')
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default waves-effect " data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-danger waves-effect waves-light "><a href="">Cancel</a></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-block">
                <div class="dt-responsive table-responsive">
                    <table id="simpletable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">{{__('ID')}}</th>
                                <th scope="col">{{__('Title')}}</th>
                                <th scope="col" width="100px">{{__('Image')}}</th>
                                <th scope="col">{{__('Status')}}</th>
                                <th scope="col">{{__('Date create')}}</th>
                                <th scope="col">{{__('Action')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($students as $key => $val)
                            <tr>
                                <th scope="row">{{ $val->id }}</th>
                                <td><a href="{{ route('web.teacher',[$val->url,$val->id]) }}" target="_blank">{{ $val->title }}</a></td>
                                <td><img width="100px" src="{{ asset($val->image) }}" alt="{{ $val->title }}"></td>
                                <td><label class="label @if($val->status == 2) bg-primary @elseif($val->status == 1) label-default @elseif($val->status == 0) label-inverse-primary @endif ">{{ $status[$val->status] }}</label></td>
                                <td>{{ $val->created_at}}</td>
                                <td>
                                    <button class="btn-primary float-left"><a href="{{ route('teachers.edit',$val->id) }}" ><i class="ti-pencil-alt"></i></i></a></button>
                                    <form action="{{route('teachers.destroy',[$val->id])}}" method="POST" class="float-left">
                                         @method('DELETE')
                                         @csrf
                                         <button type="submit" class="btn-danger" onclick="confirm('delete?')"><i class="ti-trash"></i></button>
                                    </form>
                                </td>
                                
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th scope="col">{{__('ID')}}</th>
                                <th scope="col">{{__('Title')}}</th>
                                <th scope="col">{{__('Image')}}</th>
                                <th scope="col">{{__('Status')}}</th>
                                <th scope="col">{{__('Date create')}}</th>
                                <th scope="col">{{__('Action')}}</th>
                            </tr>
                        </tfoot>
                    </table>
                    {{ $students->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection