routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(["prefix"=>"/"],function(){
	Route::get('/','Theme\RovaController@index')->name('web.index');
    Route::post('/post_mail','Theme\RovaController@post_mail')->name('web.post_mail');
    Route::get('danh-muc/{url}','Theme\RovaController@categories')->name('web.categories');
    Route::get('tags/{url}','Theme\RovaController@tags')->name('web.tags');
    Route::get('gioi-thieu/{id}','Theme\RovaController@aboutUs')->name('web.about.us');
    Route::get('lien-he','Theme\RovaController@contact')->name('web.contact');
    Route::get('chi-tiet/{id}','Theme\RovaController@chi_tiet')->name('web.chi_tiet');
    Route::get('san-pham/{id}','Theme\RovaController@san_pham')->name('web.san_pham');
    Route::get('bai-viet/{id}','Theme\RovaController@chi_tiet_tin')->name('web.chi_tiet_tin');
    Route::get('chuong-trinh-khuyen-mai','Theme\RovaController@client')->name('web.client');
    Route::get('chi-tiet-tin/{id}','Theme\RovaController@show_post')->name('web.show_post');
    Route::get('gio-hang','Theme\RovaController@cart')->name('web.cart');
    Route::get('thanh-toan','Theme\RovaController@payment')->name('web.payment');
    Route::get('tin-tuc/{id}','Theme\RovaController@post')->name('web.post');
    // Route::get('parador/{url}.html','Theme\RovaController@post')->name('web.post');
//    Route::get('san-go-parador','Theme\RovaController@products')->name('web.products');
//    Route::get('san-go-parador/{url}.html','Theme\RovaController@product')->name('web.product');
//    Route::get('san-go-parador-cao-cap/{url}.html','Theme\RovaController@productCate')->name('web.product.category');
//    Route::get('dai-ly-parador','Theme\RovaController@agents')->name('web.agents');
    Route::post('data-for-contact','Theme\RovaController@contactPost')->name('web.contact.post');
    Route::get('ho-tro-khach-hang','Theme\RovaController@member')->name('web.member');
    Route::get('loi-khong-tim-thay-trang-404','Theme\RovaController@error')->name('web.error');
    Route::get('update-cart','Theme\RovaController@updateCart')->name('web.update.cart');
    Route::get('remove-cart','Theme\RovaController@removeCart')->name('web.remove.cart');
});
Route::get('component/slider','ComponentController@slider')->name('components.slider');
/**
 *Backend adminstrator
**/
Auth::routes();
// view onlypage
	Route::get('admin/dashboard', 'HomeController@index')->name('dashboard');
	Route::get('admin/', 'HomeController@index')->name('admin');

Route::group(['prefix'=>'admin/','middleware' => ['auth']],function(){
//    user route
    Route::get('users','UserController@index')->name('user.list');
    Route::get('user/{id}','UserController@show')->name('user.show');
    Route::get('user/edit/{id}','UserController@edit')->name('user.edit');
    Route::get('user/delete/{id}','UserController@delete')->name('user.delete');
    Route::post('user/{id}','UserController@update')->name('user.update');
    Route::post('users','UserController@store')->name('user.store');
// manager file and backend custom
    Route::get('manager-file', 'BackendController@managerFile')->name('manager.file');
    Route::get('command', 'BackendController@runCommand')->name('command');
    Route::post('command', 'BackendController@postCommand')->name('command');
    Route::get('hoang-config/google-analytic','BackendController@google')->name('hoang.google');
    Route::get('hoang-config/facebook-pixel','BackendController@facebook')->name('hoang.facebook');
    Route::get('hoang-config/javascript','BackendController@javascript')->name('hoang.javascript');

//	config role of user
    Route::get('roles','RoleController@index')->name('roles.index');
    Route::get('roles/{id}/edit','RoleController@edit')->name('roles.edit');
    Route::get('roles/create','RoleController@create')->name('roles.create');
    Route::get('roles/{id}','RoleController@show')->name('roles.show');
    Route::get('roles/{id}','RoleController@destroy')->name('roles.destroy');
    Route::post('roles','RoleController@store')->name('roles.store');
    Route::post('roles/{id}','RoleController@update')->name('roles.update');
    Route::get('roles/error/403','RoleController@error')->name('roles.error');
	// Restfull function
	Route::resource('posts', PostsController::class);
    Route::get('slider','SlidersController@index')->name('slider.index');
    Route::post('slider-create','SlidersController@create')->name('slider.create');
    Route::get('slider-delete/{id}','SlidersController@destroy')->name('slider.destroy');
    Route::get('logo','LogosController@index')->name('logo.index');
    Route::post('logo-create','LogosController@create')->name('logo.create');
    Route::get('logo-delete/{id}','LogosController@destroy')->name('logo.destroy');
	Route::resource('pages', PagesController::class);
	Route::resource('products', ProductsController::class);
    Route::post('products/list-images','ProductsController@images')->name('products.images');
    Route::post('products/update-images/{id}','ProductsController@updateImages')->name('products.update.image');
    Route::get('products/images/delete/{id}','ProductsController@deleteImages')->name('products.image.delete');
    Route::get('products/edit-deal/{id}','ProductsController@editDeal')->name('products.edit.deal');


    Route::resource('categories', CategoriesController::class);
	Route::resource('tags', TagsController::class);
	Route::resource('menus', MenusController::class);
   // Route::get('menu-items/delete/{$id}','BackendController@deleteMenuItem')->name('menu-items.delete');

    Route::resource('menu-items', MenuItemsController::class);
	Route::resource('homes', HomesController::class);
	Route::resource('comments', CommentsController::class);
	Route::resource('configs', ConfigsController::class);
    Route::resource('contacts', ContactsController::class);


    Route::resource('events', EnventsController::class);
    Route::resource('members', MembersController::class);

    Route::resource('students', StudentsController::class);
    Route::resource('teachers', TeachersController::class);

    Route::resource('courses', CoursesController::class);
    Route::resource('lessons', LessonsController::class);
});

app/Http/Controllers/Theme/RovaController.php
<?php

namespace App\Http\Controllers\Theme;

use App\Entities\Category;
use App\Entities\Comment;
use App\Entities\Contact;
use App\Entities\Course;
use App\Entities\Envent;
use App\Entities\Home;
use App\Entities\Member;
use App\Entities\Post;
use App\Entities\Gmail;
use App\Entities\Product;
use App\Order;
use App\Repositories\CategoryRepository;
use App\Repositories\PostRepository;
use App\Repositories\ProductRepository;
use App\Repositories\TagRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Image;
class RovaController extends Controller
{
    public function __construct(PostRepository $postDetail,
                                ProductRepository $productDetail,
                                TagRepository $tagDetail,
                                CategoryRepository $categoryDetail
    )
    {
        $this->postDetail = $postDetail;
        $this->productDetail = $productDetail;
        $this->categoryDetail = $categoryDetail;
        $this->tagDetail = $tagDetail;

    }
    public function index(Request $request){
        if($request->mail){
            $db = new Gmail;
            $db->name = $request->mail;
            $db->save();
           }
        if ($request->go=="search"){

            $key = $request->all()['key'];
            $data['products'] = Product::where('title','like','%'.$key.'%')->orderBy('id','desc')->get();
            $data['categories'] = Category::where('type','product')->where('status',2)->get();
            $data['tim_kiem'] = $key;
            return view('search',$data);
            dd($request->all()['key']);
        }
    $data['categori']=Category::where('type','product')->where('status',2)->get();
    $data['show']=Category::where('type','product')->where('status',2)->get();
    $data['tinnoi'] = Post::orderBy('id',"desc")->limit(6)->get();
    $data['new_product'] = Product::orderBy('id',"desc")->limit(4)->get();
        return view('welcome',$data);
    }

    public function contact(){
        return view('lien_he');
    }

    public function chi_tiet($id){
    $data['san_pham'] = Product::limit(4)->get();
    $a=Product::where('id',$id)->get();
    $data['data']=$a[0];
    $data['image'] = Image::where('product_id',$id)->get();

        return view('chi_tiet_sp',$data);
    }
    public function san_pham($id){

      $data['categori']=Category::where('type','product')->where('status',2)->get();
      $data['product']=Product::orderBy('id','desc')->leftJoin('product_cates', 'product_cates.product_id', '=', 'products.id')->where('product_cates.category_id',$id)->where('deal','on')->get();
      $data['categoris']=Category::where('id',$id)->where('status',2)->get();
      $data['san_pham'] = Product::limit(5)->get();
        return view('san_pham',$data);
    }
    public function cart(Request $request){
        if (!isset($request->id)){
            $data['cart'] = new Product();
            return view('cart',$data);
        }else{


            $product = Product::find($request->id);

            if(is_null($product)) {

                return view('cart');

            }

            $cart = session()->get('cart');

            // if cart is empty then this the first product
            if(is_null($cart)) {

                $cart = [
                    $request->id => [
                        "name" => $product->title,
                        "quantity" => 1,
                        "price" => $product->price_pre,
                        "photo" => $product->image,
                        "price_pre" => $product->price
                    ]
                ];

                session()->put('cart', $cart);

                return view('cart');
            }

            // if cart not empty then check if this product exist then increment quantity
            if(isset($cart[$request->id])) {

                $cart[$request->id]['quantity']++;
                $cart[$request->id] =
                    [
                        "name" => $product->title,
                        "quantity" => $cart[$request->id]['quantity'],
                        "price" => $product->price_pre,
                        "photo" => $product->image,
                        "price_pre" => $product->price
                    ];

                session()->put('cart', $cart);

                //return redirect()->back()->with('success', 'Product added to cart successfully!');
                return view('cart');

            }

            // if item not exist in cart then add to cart with quantity = 1
            $cart[$request->id] = [
                "name" => $product->title,
                "quantity" => 1,
                "price" => $product->price_pre,
                "photo" => $product->image,
                "price_pre" => $product->price
            ];

            session()->put('cart', $cart);


            return view('cart');
        }
    }
    public function payment(){

        return view('themes.rova.thanh_toan');
    }
    public function post($id){
       $data['post']=Post::orderBy('id','desc')->leftJoin('post_cates', 'post_cates.post_id', '=', 'posts.id')->where('post_cates.category_id',$id)->paginate(8);
       $data['tinnoi'] = Post::orderBy('id',"desc")->limit(6)->get();
       // dd($data['post']);
        return view('tin_tuc',$data);
    }
    public function Show_post($id){
        $data['post'] = Post::orderBy('id','desc')->limit(8)->get();
       $a=Post::where('id',$id)->get();
       $data['data']=$a[0];
        return view('chi_tiet_tin',$data);
    }
    public function products(){
        $data['products'] = Product::where('status',2)->paginate(12);
        return view('themes.rova.products',$data);
    }
    public function product($url){
        $data['product'] = Product::where('url',$url)->first();
        $data['categories'] = Category::where('type','product')->where('status',2)->get()->all();
        $data['relate'] = Product::orderBy('id','desc')->Where('url','<>',$url)->take(6)->get();
        $data['comments'] = Comment::where('type_object','product')->where('id_object',$data['product']['id'])->where('status',1)->orderBy('id','desc')->get()->all();
//        dd($data['comments']);


        if (is_null($data['product'])){
            return view('themes.rova.404');
        }
        $data['images'] = $data['product']->images()->get()->all();
        return view('themes.rova.product',$data);
    }
    public function service($url){
        return view('themes.rova.service');
    }
    public function services(){
        return view('themes.rova.services');
    }
    public function tags($url){
        $data['tag'] = $this->tagDetail->findWhere(['url'=>$url,'type'=>'post'])->first();
        $data['posts'] = $data['tag']->posts()->orderBy('id','desc')->paginate(6);

        return view('themes.rova.blog',$data);
    }
    public function categories($url){
        $data['category'] = $this->categoryDetail->findWhere(['url'=>$url,'type'=>'post'])->first();
        $data['posts'] =  $data['category']->posts()->orderBy('id','desc')->paginate(6);
        return view('themes.rova.blog', $data);
    }
    public function productCate($url){
        $data['category'] = $this->categoryDetail->findWhere(['url'=>$url,'type'=>'product'])->first();
        $data['products'] =  $data['category']->products()->orderBy('id','desc')->paginate(6);
        return view('themes.rova.products', $data);
    }
    public function member(){
        return view('themes.rova.member');
    }
    public function agents(){
        $data['members'] = Member::orderBy('id','desc')->paginate(16);
        return view('themes.rova.agents', $data);
    }
    public function agent($url){
        return view('themes.rova.agent');
    }
    public function error(){
        return view('themes.rova.404');
    }
    public function aboutUs($id){
        $a =Post::orderBy('id','desc')->leftJoin('post_cates', 'post_cates.post_id', '=', 'posts.id')->where('post_cates.category_id',$id)->limit(1)->get();
        $data['data'] = $a[0];
        $data['category'] = Category::find($id);
        return view('gioi_thieu',$data);
    }
    public function updateCart(Request $request)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');

            $cart[$request->id]["quantity"] = $request->quantity;

            session()->put('cart', $cart);

            session()->flash('success', 'Cart updated successfully');
        }
    }
    public function contactPost(Request $request)
    {
        $con = new Contact();
        $con->name = $request->name;
        $con->phone = $request->phone;
        // $con->email = $request->email;
        // $con->address = $request->address;
        $con->note = $request->note;
        $con->save();
        $carts = session()->get('cart');
//        lưu đơn hàng
        foreach ($carts as $key => $val)
        {
            $don = new Order();
            $don->contact_id = $con->id;
            $don->product_id = $key;
            $don->name = $val['name'];
            $don->quantity = $val['quantity'];
            $don->price = $val['price'];

            $don->save();
        }
        session()->flush();
        return redirect()->back();
    }
    public function removeCart(Request $request)
    {
        $cart = session()->get('cart');

        if(isset($request->id)) {

            unset($cart[$request->id]);

            session()->put('cart', $cart);
        }

        session()->flash('success', 'Product removed successfully');
        return redirect()->route('web.cart');
    }

}

resources/views/themes/rova/404.blade.php
@extends('themes.rova.layouts.design')
@section('title',"Lỗi tìm kiếm trang 404")
@section('description',"Parador Việt Nam hiện không thể truy cập đến đường dẫn hiện tại")

@section('content')
    <!-- Start page content -->
    <section id="page-content" class="page-wrapper">

        <!-- ERROR AREA START -->
        <div class="error-area ">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="error-content ">
                            <h2>404</h2>
                            <h3>Không tìm thấy trang!</h3>
                            <h4>Cảnh báo! Có vẻ như trang không được tình thấy.</h4>
                            <p>Chúng thôi không thể tìm thấy trang bạn cần truy cập <br>
                                Hãy đảm bảo url truy cập hiên tại là đúng</p>
                            <a class="go-home" href="{{ route('web.index') }}">Về trang chủ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ERROR AREA END -->
        @include('themes.rova.layouts.subscribe')
    </section>
    <!-- End page content -->

@endsection

resources/views/themes/rova/post.blade.php
@extends('themes.rova.layouts.design')
@if(is_null($post->meta_title) && is_null($post->meta_des))
    @section('title',$post->title.'- Sàn gỗ Parador')
@section('description',$post->des)
@else
    @section('title',$post->meta_title.'- Sàn gỗ Parador')
@section('description',$post->meta_des)
@endif
@section('image',asset($post->image))
@section('content')


    <!-- BREADCRUMBS AREA START -->
    <div class="breadcrumbs-area bread-bg-1 bg-opacity-black-70">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="breadcrumbs">
                        <h2 class="breadcrumbs-title">{{ $post->title }}</h2>
                        <ul class="breadcrumbs-list">
                            <li><a href="{{ route('web.index') }}">Parador</a></li>
                            <li><a href="{{ route('web.blog') }}">Tin tức</a></li>
                            <li>Chi tiết</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BREADCRUMBS AREA END -->
    @if(isset(Auth::user()->name))
        <div class="">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="">
                            <span>Xin chào: <strong>{{ Auth::user()->name }}</strong></span>
                            <span>| Chức năng dành cho quản trị viên: <a href="{{route('posts.edit',$post->id)}}" class="btn btn-primary">Sửa bài viết</a></span>
                            <span><a class="btn btn-default" href="{{route('dashboard')}}">Quản trị</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif
    <!-- Start page content -->
    <section id="page-content" class="page-wrapper">

        <!-- BLOG AREA START -->
        <div class="blog-area pt-115 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-xs-12">
                        <div class="blog-details-area">
                            <!-- blog-details-image -->
                           {{-- <div class="blog-details-image text-center">
                                <img class="img-fluid" src="{{ asset($post->image) }}" alt="{{ $post->title }}">
                            </div>--}}
                            <!-- blog-details-title-time -->
                            <div class="blog-details-title-time">
                                <h5>{{ $post->title }}</h5>
                                <p>{{ date_format($post->created_at,'d-m-Y, h A') }}</p>
                            </div>
                            <!-- blog-details-desctiption -->
                            <div class="blog-details-desctiption mb-60">
                                {!! $post->content !!}
                            </div>
                            <!-- blog-details-share-tags -->
                            <div class="blog-details-share-tags clearfix mb-75">
                                <div class="blog-details-tags f-left">
                                    <ul>
                                        <li>Tags :</li>
                                        @foreach($post->tags as $key => $val)
                                        <li><a href="{{ route('web.tags',$val->url) }}">@if($key == 0) @else , @endif {{ $val->name }}</a></li>
                                        @endforeach

                                    </ul>
                                </div>
                                <div class="blog-details-share f-right">
                                    <ul class="social-media">
                                        <li>Share:</li>
                                        <li><a href="#!"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                        <li><a href="#!"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li><a href="#!"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                        <li><a href="#!"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <!-- blog-details-author-post -->
                            <div class="blog-details-author-post clearfix line-bottom pb-30 mb-115">
                                <div class="blog-details-author-image">
                                    <a href="#!"><img src="{{ asset('theme/rova/images/avatar/2.jpg') }}" alt="admin parador"></a>
                                </div>
                                <div class="blog-details-author-desc">
                                    <div class="blog-details-author-name">
                                        <h6><a href="#!">Sàn Gỗ Đức Cao Cấp Parador</a></h6>
                                        <p class="">Quản trị Parador</p>
                                    </div>
                                    <p> <strong>PARADOR</strong> tự hào là công ty đi đầu về nội thất. Chúng tôi luôn mang đến cho khách hàng sự thoải mái nhất.</p>
                                </div>
                            </div>
                            <!-- pro-details-feedback -->
                            <div class="pro-details-feedback mb-100">
                                <h5>{{ count($comments) }} Bình luận</h5>
                                <!-- media -->
                                @foreach($comments as $key => $val)
                                <div class="media">
                                    <a class="media-left" href="#">
                                        <img src="{{ asset('theme/rova/images/avatar/1.jpg') }}" alt="">
                                    </a>
                                    <div class="media-body">
                                        <h6 class="media-heading"><a href="#!">{{ $val->name }}</a></h6>
                                        <p><span>{{ date_format($val->created_at,'d-m-Y / h A') }}</span>{{ $val->content }}</p>

                                    </div>
                                </div>
                                @endforeach
                            </div>
                            <!-- blog-details-reply -->
                            <div class="blog-details-reply leave-review">
                                <h5>Bình luận bài viết</h5>
                                <label id="cmt-note" class="form-control hidden"></label>
                                <form action="#">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" name="name" placeholder="Your name" id="cmt-name">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="email" name="email" placeholder="Email" id="cmt-email">
                                        </div>
                                    </div>
                                    <textarea placeholder="Write here" id="cmt-content"></textarea>
                                    <button type="reset" class="submit-btn-1" onclick="sendCommnet();">Gửi Bình luận</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12">
                        <!-- widget-search -->
                       {{-- <aside class="widget widget-search mb-30">
                            <form action="#">
                                <input type="text" name="search" placeholder="Search...">
                                <button type="button" class=""><i class="fa fa-search" aria-hidden="true"></i></button>
                            </form>
                        </aside>--}}
                        <!-- widget-categories -->
                        <aside class="widget widget-categories mb-50">
                            <h5>Categories</h5>
                            <ul class="widget-categories-list">
                                @foreach($categories as $k => $val)
                                <li><a href="{{ route('web.categories',$val->url) }}">{{ $val->name }} <span>{{ $val->posts->count() }}</span></a></li>
                                @endforeach
                            </ul>
                        </aside>
                        <!-- widget-recent-post -->
                        <aside class="widget widget-recent-post mb-50">
                            <h5>Bài viết gần đây</h5>
                            <div class="row">
                                <!-- blog-item -->
                                @foreach($posts as $k => $val)
                                    <div class="col-md-12 col-sm-6 col-xs-12">
                                        <article class="recent-post-item">
                                            <div class="recent-post-image">
                                                <a href="{{ route('web.post',$val->url) }}"><img src="{{ asset($val->image) }}" alt="{{ $val->title }}"></a>
                                            </div>
                                            <div class="recent-post-info">
                                                <div class="recent-post-title-time">
                                                    <h5><a href="{{ route('web.post',$val->url) }}">{{ $val->title }}</a></h5>
                                                    <p>{{ date_format($val->created_at,'d-m-Y / h A') }}</p>
                                                </div>
                                                <p>{{ $val->des }}</p>
                                            </div>
                                        </article>
                                    </div>
                                @endforeach
                            </div>
                        </aside>

                    </div>
                </div>
            </div>
        </div>
        <!-- BLOG AREA END -->

        @include('themes.rova.layouts.subscribe')
    </section>
    <!-- End page content -->
@stop
@section('js')
    <script>

        function postData(url = '', data = {}) {
            // Default options are marked with *
            return fetch(url, {
                method: 'POST', // *GET, POST, PUT, DELETE, etc.
                mode: 'cors', // no-cors, cors, *same-origin
                cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
                credentials: 'same-origin', // include, *same-origin, omit
                headers: {
                    'Content-Type': 'application/json',
                    // 'Content-Type': 'application/x-www-form-urlencoded',
                },
                redirect: 'follow', // manual, *follow, error
                referrer: 'no-referrer', // no-referrer, *client
                body: JSON.stringify(data), // body data type must match "Content-Type" header
            })
                .then(response => response.json()); // parses JSON response into native JavaScript objects
        }
        var url = "{{ route('webapi.contact') }}";
        function sendCommnet() {
            var send1 = {name: $('#cmt-name').val(),
                email: $('#cmt-email').val(),
                content: $('#cmt-content').val(),
                id: "{{$post->id}}",
                type: "post",
            };
            //alert(JSON.stringify(send1));
            postData(url, send1)
                .then(function (data1) {
                    // console.log(data1.status);
                    if (data1.status) {
                        $("#cmt-note").removeClass('hidden').addClass("alert-success").html(data1.note);
                    }else {
                        $("#cmt-note").removeClass('hidden').addClass("alert-warning").html(data1.note);
                    }
                }) // JSON-string from `response.json()` call
                .catch(error => console.error(error));

        }

    </script>
@endsection